fix <git>: take into account pushing into new branch on pre-push hook

diff --git a/.config/git/hooks/pre-push b/.config/git/hooks/pre-push
--- a/.config/git/hooks/pre-push
+++ b/.config/git/hooks/pre-push
@@ -1,20 +1,27 @@
 #!/bin/bash
 
-# Read the push details
+set -e
+
+zero_sha="0000000000000000000000000000000000000000"
+
 while read -r _local_ref local_sha _remote_ref remote_sha; do
-	# Get the list of commits being pushed
-	commits=$(git rev-list "$remote_sha".."$local_sha")
+	# Determine commit range
+	if [[ "$remote_sha" == "$zero_sha" ]]; then
+		# New branch or first push
+		commits=$(git rev-list "$local_sha")
+	else
+		commits=$(git rev-list "$remote_sha".."$local_sha")
+	fi
 
-	# Check each commit message
 	for commit in $commits; do
-		message=$(git log --format=%B -n 1 "$commit")
+		message=$(git log -1 --format=%B "$commit")
 
-		if [[ $message == fixup* ]]; then
-			echo -e "\e[31mError fixup pending: '\e[46m\e[31m$message\e[0m\e[31m'. Aborting push.\e[0m"
+		if [[ "$message" == fixup!* ]]; then
+			echo -e "\e[31mError - fixup commit pending: \e[46m\e[31m$message\e[0m"
+			echo -e "\e[31mPlease squash or autosquash before pushing.\e[0m"
 			exit 1
 		fi
 	done
 done
 
-# Allow the push if no commit messages start with 'fixup'
 exit 0
